### ISSUE TITLE
Juju: Make it more object-oriented

### ISSUE THREAD

**Issue by davidfischer-ch** [davidfischer-ch/pytoolbox#14]
# Tasks
- [ ] Implement service class
- [ ] Implement machine class
- [ ] Implement unit class
- [ ] Mark most of the Environment class methods as deprecated

**Comment by davidfischer-ch** [comment]
Unfortunately I am probably not going to use juju for a while ...
